### ISSUE TITLE
Trouble installing tw_gcal_sync "You have to install the [gcal] extra"

### ISSUE THREAD

**Issue by lorenzojavier** [bergercookie/taskwarrior-syncall#33]
Greetings, and thank you for your attention. I have some trouble installing this tool.

First, I installed tw_gcal_sync using:

`pip3 install --user --upgrade taskwarrior-syncall`

Then I tried running:

```
tw_gcal_sync -c "Tasks" -t "gcal" --gcal-secret "/home/lorenzo/Documents/00 Bandeja de Entrada/Taskwarrior Calendar Sync/client_secret_702189409220-ho9fohj3foiia95u4m49e0ojbjste6ln.apps.googleusercontent.com.json"
```
And got this:
```
2022-03-30 13:18:26.424 | ERROR    | taskwarrior_syncall.scripts.tw_gcal_sync:<module>:10 - You have to install the [gcal] extra for /home/lorenzo/.local/bin/tw_gcal_sync to work. Exiting.
```

I use Elementary OS Jólnir, my Taskwarrior version is 2.6.2.

What may be wrong here?
Thanks again to anybody who reads this :)

**Comment by bergercookie** [comment]
Hi @lorenzojavier ,

Yeah, I should be documenting this better. You have to add the `pip` extra for your usecase since this tool supports synchronization with multiple sources now.

For gcal, you should be installing it with something like the following:

```
pip3 install --user --upgrade taskwarrior-syncall[gcal]
```

If you want to add support for both google calendar and notion, you sould be using:

```
pip3 install --user --upgrade taskwarrior-syncall[gcal,notion]
```

**Comment by bergercookie** [comment]
Added more detailed instructions as part of the error message in the latest master and latest pypi prerelease
